- hosts: dockerswarm
  become: true
  become_user: root
  tasks:
   - name: Install docker
     yum:
      name: docker
      state: present
   - name: Start Docker Service
     service:
      name: docker
      state: started
 
